Lab 2
-- Built-in Function
--1.Built-in Function  Display actor names in the format: LAST_NAME, First_name (e.g., GUINESS, Penelope).
SELECT CONCAT(UPPER(last_name), ', ', first_name) AS formatted_name FROM actor;

--2. Display all customer emails in lowercase and replace the domain @sakilacustomer.org with @iti-students.edu.
SELECT REPLACE(LOWER(email), '@sakilacustomer.org', '@iti-students.edu') AS formatted_email FROM customer;

--3. Display the first 50 characters of each film's description followed by "..." and call the column short_summary.
SELECT CONCAT(LEFT(description, 50), '...') AS short_summary FROM film;

--4. Find all customers who registered in the month of February (any year).
SELECT first_name, last_name, email FROM customer 
WHERE MONTH(create_date) = 2;

--5. Extract the Quarter (1, 2, 3, or 4) from the payment_date (payment table) to see which part of the year is most profitable.
SELECT payment_id, payment_date, QUARTER(payment_date) AS payment_quarter FROM payment;

--6. Use CASE to label rentals as 'Cheap' (under $2), 'Mid' ($2-$4.99), or 'Expensive' (above $5).
SELECT rental_id, rental_date,
CASE 
  WHEN rental_rate < 2 THEN 'Cheap' 
  WHEN rental_rate BETWEEN 2 AND 4.99 THEN 'Mid' 
  ELSE 'Expensive' 
END AS price_category
FROM rental;


-- User-Defined Functions
--1. Create a function that takes actor_id and returns the concatenated first and last name of this actor.
delimiter /
CREATE FUNCTION get_actor_name(actor_id INT)
RETURNS VARCHAR(255)
not deterministic reads sql data
BEGIN
  DECLARE full_name VARCHAR(255);
  SELECT CONCAT(first_name, ' ', last_name) INTO full_name 
  FROM actor 
  WHERE actor.actor_id = actor_id;
  RETURN full_name;
END /
delimiter ;

--2. Create a function that takes customer_id and returns the total count of rentals made by this customer.
delimiter /
CREATE FUNCTION get_rental_count(customer_id INT)
RETURNS INT
not deterministic reads sql data
BEGIN
  DECLARE rental_count INT;
  SELECT COUNT(*) INTO rental_count 
  FROM rental 
  WHERE rental.customer_id = customer_id;
  RETURN rental_count;
END /
delimiter ;

--3. Create a function that takes a DECIMAL value and returns it as a formatted string with a dollar sign (e.g., $19.99).
delimiter /
CREATE FUNCTION format_currency(amount DECIMAL(10,2))
RETURNS VARCHAR(20)
not deterministic reads sql data
BEGIN
  RETURN CONCAT('$', FORMAT(amount, 2));
END /
delimiter ;

-- Stored Procedures
--4. Create a stored procedure that takes customer_id and returns a result set containing the full name, email, full address, and city of that customer.
delimiter /
CREATE PROCEDURE get_customer_info(IN cust_id INT)
BEGIN
  SELECT 
    CONCAT(first_name, ' ', last_name) AS full_name,
    email,
    CONCAT(address, ', ', city) AS full_address
  FROM customer 
  JOIN address ON customer.address_id = address.address_id 
  JOIN city ON address.city_id = city.city_id 
  WHERE customer.customer_id = cust_id;
END /
delimiter ;


--5. Create a stored procedure that takes a start_date and end_date and returns the total revenue generated by each store during that period.
delimiter /
CREATE PROCEDURE get_store_revenue(IN start_date DATE, IN end_date DATE)
BEGIN
  SELECT store_id, SUM(amount) AS total_revenue 
  FROM payment 
  WHERE payment_date BETWEEN start_date AND end_date 
  GROUP BY store_id;
END /
delimiter ;

--6. Create a stored procedure that takes a partial string (e.g., 'dark') and returns all films whose titles contain that string, along with their ratings.
delimiter /
CREATE PROCEDURE search_films_by_title(IN partial_title VARCHAR(255))
BEGIN
  SELECT title, rating 
  FROM film 
  WHERE title LIKE CONCAT('%', partial_title, '%');
END /
delimiter ;


--7. Create a stored procedure that takes customer_id and returns the name of the category (e.g., 'Action') that the customer rents most often.
delimiter /
CREATE PROCEDURE get_favorite_category(IN cust_id INT)
BEGIN
  SELECT category.name AS favorite_category
  FROM customer
  JOIN rental ON customer.customer_id = rental.customer_id
  JOIN inventory ON rental.inventory_id = inventory.inventory_id
  JOIN film ON inventory.film_id = film.film_id
  JOIN film_category ON film.film_id = film_category.film_id
  JOIN category ON film_category.category_id = category.category_id
  WHERE customer.customer_id = cust_id
  GROUP BY category.name
  ORDER BY COUNT(*) DESC
  LIMIT 1;
END /
delimiter ;


-- Trigger
--8. Create a BEFORE UPDATE trigger on address table to set last_update = NOW() whenever a row is changed.
delimiter /
CREATE TRIGGER update_address_last_update
BEFORE UPDATE ON address
FOR EACH ROW
SET NEW.last_update = NOW();
/
delimiter ;

--9. Create a trigger to prevent an UPDATE to the staff table if the username is changed to 'admin'.
delimiter /
CREATE TRIGGER prevent_admin_username
BEFORE UPDATE ON staff
FOR EACH ROW
BEGIN
  IF NEW.username = 'admin' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot change username to admin';
  END IF;
END /
delimiter ;


--10. Create a BEFORE INSERT trigger on the customer table to ensure that any email address entered contains both an @ and a . symbol.
delimiter /
CREATE TRIGGER validate_customer_email
BEFORE INSERT ON customer
FOR EACH ROW
BEGIN
  IF NEW.email NOT REGEXP '^[^@]+@[^@]+\.[^@]+$' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid email format';
  END IF;
END /
delimiter ;


--11. Create a table film_price_history. Create an AFTER UPDATE trigger on the film table that records the old price, new price, and change date whenever the rental_rate is modified.
create table film_price_history (
  history_id INT AUTO_INCREMENT PRIMARY KEY,
  film_id INT,
  old_price DECIMAL(4,2),
  new_price DECIMAL(4,2),
  change_date DATETIME
);
delimiter /
CREATE TRIGGER record_price_change
AFTER UPDATE ON film
FOR EACH ROW
BEGIN
  IF OLD.rental_rate != NEW.rental_rate THEN
    INSERT INTO film_price_history (film_id, old_price, new_price, change_date)
    VALUES (NEW.film_id, OLD.rental_rate, NEW.rental_rate, NOW());
  END IF;
END /
delimiter ;
