# Generated by Django 5.2.13 on 2026-04-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
